server:
  port: 8080
logging:
  file: logs/log.log

spring:
  thymeleaf:
    cache: false #\u5F00\u53D1\u65F6\u8981\u5173\u95ED\u7F13\u5B58\uFF0C\u5426\u5219\u770B\u4E0D\u5230\u9875\u9762
    encoding: utf-8
    servlet:
      content-type: text/html

  datasource:
        url: jdbc:mysql://localhost:3306/taiir_paramstest?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC
        #    url: jdbc:mysql://localhost:3306/sputdemo?
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        druid:
          initial-size: 5
          max-active: 50
          max-wait: 3000
          use-unfair-lock: true
          pool-prepared-statements: false
          filters: stat,log4j,wall
          validation-query: select 1
          validation-query-timeout: 3000
          test-on-borrow: true
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 5000


#    #\u8868\u793A\u8BE5\u914D\u7F6E\u76F4\u63A5\u4E3ASpring\u5BB9\u5668\u8D1F\u8D23\u5904\u7406
#\u3000\u3000datasource:
#  \u3000\u3000type: com.alibaba.druid.pool.DruidDataSource   #\u914D\u7F6E\u5F53\u524D\u8981\u4F7F\u7528\u7684\u6570\u636E\u6E90\u7684\u64CD\u4F5C\u7C7B\u578B\u90A3\u4E2A
#  \u3000\u3000driver-class-name:  com.mysql.jdbc.Driver  #\u914D\u7F6EMySQL\u7684\u9A71\u52A8\u7A0B\u5E8F\u7C7B
#  \u3000\u3000url: jdbc:mysql://localhost:3306/taiir_paramstest?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC
#
#  \u3000\u3000username: root
#  \u3000\u3000password: root
#  \u3000\u3000filters: stat,wall,log4j     #druid\u76D1\u63A7\u914D\u7F6E
#  \u3000\u3000dbcp2:
#    \u3000\u3000min-idle: 5         #\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u7EF4\u6301\u8FDE\u63A5\u6570
#    \u3000\u3000initial-size: 5     #\u521D\u59CB\u5316\u63D0\u4F9B\u7684\u8FDE\u63A5\u6570
#    \u3000\u3000max-total: 5          #\u6700\u5927\u7684\u8FDE\u63A5\u6570
#    \u3000\u3000max-wait-millis: 200        #\u7B49\u5F85\u8FDE\u63A5\u83B7\u53D6\u7684\u6700\u5927\u8D85\u65F6\u65F6\u95F4
